### ISSUE TITLE
No method to auto prefix the database table names from an environment variable

### ISSUE THREAD

**Issue by StephanieSunshine** [gregory/locomotive_cms#1]
I've noticed that there is no easy way to set a unique database prefix from the docker run command.  Trying to start more than one locomotive_cms on a server with the same database backend creates a database collision when trying to start unique locomotives.  

I propose an environment such as MONGODB_PREFIX or something that allows us to prefix _development, _testing, _production from the docker run "-e" comand.

**Comment by gregory** [comment]
Feel free to open PR. I'm good with the MONGODB_PREFIX.
