### ISSUE TITLE
No method to change SMTP host from an environment variable

### ISSUE THREAD

**Issue by StephanieSunshine** [gregory/locomotive_cms#2]
Hi, I would like to be able to use Mandrill with this image.  The main thing that needs to be allowed to change is the SMTP host in the mail settings.

**Comment by gregory** [comment]
I'm a little busy lately, so feel free to open PR. 
i'd then rename all the the env variables to remove all the SENDGRID mentions and make it more general like: 

SMTP_USERNAME, SMTP_PASSWORD, SMTP_DOMAIN, SMTP_ADDRESS etc. 

and make sure there is defaults if no env. ex: ENV[SMTP_enable_starttls_auto] || true
